global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs: 
- job_name: prometheus
  scrape_interval: 5s
  scrape_timeout: 2s
  honor_labels: true
  static_configs:
    - targets: ['127.0.0.1:9090']

- job_name: 'app'
  scrape_interval: 5s
  static_configs:
    - targets: ['urlshortener:8000']